"""
Bonus router — AI text detection and media/deepfake detection endpoints.
"""

import json
import base64
import groq
from fastapi import APIRouter, UploadFile, File, Form
from pydantic import BaseModel
from typing import Optional

from app.config import GROQ_API_KEY, GROQ_MODEL
from app.utils.prompts import (
    AI_DETECTION_SYSTEM_PROMPT,
    AI_DETECTION_USER_PROMPT,
    MEDIA_DETECTION_SYSTEM_PROMPT,
    MEDIA_DETECTION_USER_PROMPT,
)

# Configure Groq
client = groq.Groq(api_key=GROQ_API_KEY)

router = APIRouter()


class AIDetectionRequest(BaseModel):
    """Request body for AI text detection."""
    text: str


@router.post("/detect-ai")
async def detect_ai_text(request: AIDetectionRequest):
    """
    POST /detect-ai — Detect if text was generated by AI.
    
    Accepts:
        - text: The text to analyze
        
    Returns:
        JSON with AI detection analysis, confidence, and indicators.
    """
    try:
        prompt = AI_DETECTION_USER_PROMPT.format(input_text=request.text)
        
        completion = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": AI_DETECTION_SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            temperature=0.1,
            max_tokens=4096,
            response_format={"type": "json_object"}
        )
        
        response_text = completion.choices[0].message.content.strip()
        result = json.loads(response_text)
        return {"success": True, "result": result}
    
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": f"Failed to parse AI detection response: {str(e)}",
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"AI detection error: {str(e)}",
        }


@router.post("/detect-media")
async def detect_media_manipulation(
    file: UploadFile = File(...),
    description: Optional[str] = Form(None),
):
    """
    POST /detect-media — Detect manipulated/deepfake media.
    
    Accepts:
        - file: Image file to analyze (multipart upload)
        - description: Optional description of the image context
        
    Returns:
        JSON with manipulation detection analysis, confidence, and indicators.
    """
    try:
        # Read the uploaded file
        contents = await file.read()
        
        # Determine MIME type
        content_type = file.content_type or "image/jpeg"
        
        # Groq Vision structure
        content_items = [
            {"type": "text", "text": MEDIA_DETECTION_SYSTEM_PROMPT + "\n\n" + MEDIA_DETECTION_USER_PROMPT}
        ]
        
        if description:
            content_items.insert(0, {"type": "text", "text": f"Context: {description}\n\n"})
            
        content_items.append({
            "type": "image_url",
            "image_url": {
                "url": f"data:{content_type};base64,{b64_data}",
            }
        })
        
        completion = client.chat.completions.create(
            model="llama-3.2-11b-vision-preview",
            messages=[
                {"role": "user", "content": content_items}
            ],
            temperature=0.1,
            max_tokens=4096,
        )
        
        response_text = completion.choices[0].message.content.strip()
        
        import re
        json_match = re.search(r'```(?:json)?\s*(.*?)\s*```', response_text, re.DOTALL)
        if json_match:
            response_text = json_match.group(1).strip()
        else:
            start = response_text.find('{')
            end = response_text.rfind('}')
            if start != -1 and end != -1:
                response_text = response_text[start:end+1]
        
        result = json.loads(response_text)
        return {"success": True, "filename": file.filename, "result": result}
    
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": f"Failed to parse media detection response: {str(e)}",
        }
    except Exception as e:
        return {
            "success": False,
            "error": f"Media detection error: {str(e)}",
        }
